### ISSUE TITLE
estimatedDeliveryDate is undefined always

### ISSUE THREAD

**Issue by govindtotla** [anatelli10/ts-shipment-tracking#1]
i am getting estimatedDeliveryDate: undefined always. see the below response.

Is it something related to my account permissions or some technical glitch?

![image](https://user-images.githubusercontent.com/2527901/137544296-1a1ffe65-82b6-45d8-9623-054c8c9ab2fe.png)

**Comment by anatelli10** [comment]
Hi, thanks for using this module and posting this issue. 

In this example, if the FedEx API response does not contain a property called `EstimatedDeliveryTimestamp`, then `estimatedDeliveryDate` will be undefined. If you can see an estimated delivery date on the FedEx website but not here, then please email the tracking number to me at anatelli10@gmail.com (for your own privacy as personal information is attached to tracking numbers) and I will look into it. Thanks!

**Comment by govindtotla** [comment]
yes, I tried to log the complete object and tried different keys as following
1. EstimatedDeliveryTimestamp
2. OriginalEstimatedDeliveryTimestamp
3. estimatedDeliveryTimeWindow   ( https://developer.fedex.com/api/en-us/catalog/track/v1/docs.html#operation/Track%20Multiple%20Piece%20Shipment)

well but nothing seems working. but as you have mentioned that you can see the estimated delivery time, then it should be there in the response. I am sending you my tracking number by email. and let me know if we can connect on google meet or something similar.
Thanks
Govind, India
